### ISSUE TITLE
Data -.inf drive_module_steering_angle_controller

### ISSUE THREAD

**Issue by peterheim1** [pvandervelde/zinger_swerve_controller#1]
Hi 
very impressed with your work
I tried the zinger_swerve_controller for my swerve robot but when you stop the robot the
drive_module_steering_angle_controller/commands data shows 

```
layout:
  dim: []
  data_offset: 0
data:
- -.inf
- -.inf
- -.inf
- -.inf
```

if /cmd_vel is not 0 then no inf 
trying to convert them to a INT I get
OverflowError: cannot convert float infinity to integer
